/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    /**
     * MediumButton web component
     * <medium-button />
     */
    interface MediumButton {
        /**
          * Enables disabled state
         */
        "isDisabled": boolean;
        /**
          * Enables loading effect
         */
        "isLoading": boolean;
    }
}
declare global {
    /**
     * MediumButton web component
     * <medium-button />
     */
    interface HTMLMediumButtonElement extends Components.MediumButton, HTMLStencilElement {
    }
    var HTMLMediumButtonElement: {
        prototype: HTMLMediumButtonElement;
        new (): HTMLMediumButtonElement;
    };
    interface HTMLElementTagNameMap {
        "medium-button": HTMLMediumButtonElement;
    }
}
declare namespace LocalJSX {
    /**
     * MediumButton web component
     * <medium-button />
     */
    interface MediumButton {
        /**
          * Enables disabled state
         */
        "isDisabled"?: boolean;
        /**
          * Enables loading effect
         */
        "isLoading"?: boolean;
    }
    interface IntrinsicElements {
        "medium-button": MediumButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * MediumButton web component
             * <medium-button />
             */
            "medium-button": LocalJSX.MediumButton & JSXBase.HTMLAttributes<HTMLMediumButtonElement>;
        }
    }
}
